// <auto-generated />
namespace AccesoADatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDNI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDNI));
        
        string IMigrationMetadata.Id
        {
            get { return "201508280108272_AddDNI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
